environment: dev
dev:
    phraseanet:
        servername: 'http://local.phrasea/'
        maintenance: false
        debug: true
        display_errors: true
        database: main_connexion
    template_engine: twig_debug
    orm: doctrine_dev
    cache: array_cache
    opcodecache: array_cache
    border-manager: border_manager
prod:
    phraseanet:
        servername: 'http://local.phrasea/'
        maintenance: false
        debug: false
        display_errors: false
        database: main_connexion
    template_engine: twig
    orm: doctrine_prod
    cache: array_cache
    opcodecache: array_cache
    border-manager: border_manager
test:
    phraseanet:
        servername: 'http://local.phrasea/'
        maintenance: false
        debug: true
        display_errors: true
        database: main_connexion
    template_engine: twig_debug
    orm: doctrine_test
    cache: array_cache
    opcodecache: array_cache
    border-manager: border_manager
