---
# Application tasks to be customized and to run after the main provision
- name: Install global npm packages
  become: yes
  become_user: vagrant
  shell: export NVM_DIR="$HOME/.nvm" &&. "$NVM_DIR/nvm.sh" && npm install -g bower recess

- name: Initialize application configuration
  become: yes
  become_user: vagrant
  shell: 'bin/setup system:install --email=admin@{{ hostname }}.vb --password=admin --db-host=127.0.0.1 --db-port=3306 --db-user={{ mariadb.user }} --db-password={{ mariadb.password }} --db-template=fr --appbox={{ mariadb.database }} --databox={{ mariadb.databox_db }} --server-name=www.{{ hostname }}.vb --data-path=/vagrant/datas -y'
  args:
    chdir: /vagrant/
